#!/usr/bin/env bash
set -e

. tools/lib/testing

main() {
	filename="$1"
	if [[ "$filename" == "" ]]; then
		echo "Usage: $0 <filename> [\"\"|example|test]" >&2
		return 1
	fi

	fns=( $(testing::fns "$filename") )
	if (( ${#fns[@]} == 0 )); then
		printf "No functions found in %q\n" "$filename" >&2
		return 1
	fi

	out=$(mktemp -d "/tmp/factl.XXXXXX")
	trap "rm -r $out" EXIT

	for fn in "${fns[@]}"; do
		echo "Running $fn()" >&2

		if testing::run "$filename" "$fn"; then
			echo "  PASSED" >&2
		else
			echo "  FAILED" >&2
			return 1
		fi
	done
}

main "$@"
