name: Tests

on:
  push:
  pull_request:

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Nix shell
        uses: diamondburned/cache-install@d35fbc312958f4c121770767d74a3b49fbe0f280

      - name: Run tests
        run: ./tools/test-all
